spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/country_phone
    driver-class-name: com.mysql.jdbc.Driver
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  profiles:
    include: ${SPRING_ACTIVE_PROFILES}, urls

app:
  allow-quartz: false
  phone:
    mask: ${PHONE_NUMBER_MASK:^(\d{1,3}( )?)?((\(\d{3}\))|\d{3})[- .]?\d{3}[- .]?\d{4}$}
  wiki:
    article-url: ${WIKI_ARTICLE_URL:https://en.wikipedia.org/wiki/List_of_country_calling_codes#Ordered_by_code}
    country-phone-line-tag: ${WIKI_COUNTRY_PHONE_LINE_TAG:ul li}
    country-phone-tag: ${WIKI_COUNTRY_PHONE_TAG:a}
    phone-first-char: ${WIKI_PHONE_FIRST_CHAR:+}
    phone-diff-separator: ${WIKI_DIFF_PHONES_SEPARATOR:/}
    phone-any-num-mask: ${WIKI_ANY_NUM_MASK:x}
    cron-schedule: ${WIKI_UPDATE_CRON:0 * 23 ? * *}
    allow-update-on-start: true
